#!/bin/sh -e

#
# This script is inspired by coreos/etcd.
# The credits goes to coreos.
# This version is only a (slightly) modified version.
#
# Thanks to open source and thanks to CoreOS / etcd.
#
# @link https://github.com/coreos/etcd/blob/master/scripts/build-release
#

VER=$1
PROJ="TrendingGithub"

if [ -z "$1" ]; then
	echo "Usage: ${0} VERSION" >> /dev/stderr
	exit 255
fi

set -u

function main {
	mkdir release

	for os in darwin windows linux; do
		export GOOS=${os}
		export GOARCH="amd64"

		TARGET="TrendingGithub-${VER}-${GOOS}-${GOARCH}"
		mkdir ${TARGET}
		cp README.md ${TARGET}/README.md

		local ext=""
		if [ ${GOOS} == "windows" ]; then
			ext=".exe"
		fi

		go build -o ${TARGET}/TrendingGithub${ext}

		if [ ${GOOS} == "linux" ]; then
			tar cfz release/${TARGET}.tar.gz ${TARGET}
			echo "Wrote release/${TARGET}.tar.gz"
		else
			zip -qr release/${TARGET}.zip ${TARGET}
			echo "Wrote release/${TARGET}.zip"
		fi
	done
}

main
